"""add updatedAt column to blogs

Revision ID: 14b6bcf41b6a
Revises: 3f3202c22005
Create Date: 2026-01-07 15:02:04.567030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b6bcf41b6a'
down_revision: Union[str, Sequence[str], None] = '3f3202c22005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
