"""add_featured_images_array

Revision ID: ed8dc2ba68c9
Revises: d3a8b9c5e7f1
Create Date: 2026-01-01 16:06:45.042980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8dc2ba68c9'
down_revision: Union[str, Sequence[str], None] = 'd3a8b9c5e7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
