"""add updatedAt column

Revision ID: f0817d7c7e2c
Revises: ed8dc2ba68c9
Create Date: 2026-01-02 14:25:23.307611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0817d7c7e2c'
down_revision: Union[str, Sequence[str], None] = 'ed8dc2ba68c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
